version: '3'

services:

    reverse-proxy:
        image: nginx:1.17.10
        container_name: reverse_proxy_demo
        depends_on:
            - pagina1
            - pagina2
            - pagina3
            - laravel
            - bdlaravel
            - acortador
            - bdacortador
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
    pagina1:
        image: onlychiefy/nginx-multisite-test:1.2
        restart: always
        ports: 
        - 400:80
    pagina2:
        image: onlychiefy/nginx-multisite-test:1.3
        restart: always
        ports: 
        - 4100:80
    acortador:
        image: onlychiefy/nginx-multisite-test:1.7
        restart: always
        ports: 
        - 4500:80
    pagina3:
        image: onlychiefy/nginx-multisite-test:1.4
        restart: always
        ports: 
        - 4200:80
    laravel:
        image: onlychiefy/nginx-multisite-test:1.5
        restart: always
        ports: 
        - 4300:80
    bdlaravel:
        image: onlychiefy/nginx-multisite-test:1.6
        restart: always
        ports: 
        - 4400:80
    
    bdacortador:
        image: onlychiefy/nginx-multisite-test:1.8
        restart: always
        ports: 
        - 4900:80







